### ISSUE TITLE
Indicate that a listener is notified for all event types (in the list of listeners)

### ISSUE THREAD

**Issue by pedesen** [bpmn-io/cmmn-js-properties-panel#47]
Maybe display the listener as "all: JavaClass" or remove the leading colon?

![variable_listener_all](https://cloud.githubusercontent.com/assets/2543743/16340080/6b04866c-3a26-11e6-8f49-62b17a5b06e6.png)

affects TaskListener, CaseExecutionListener and VariableListener

**Comment by polenz** [comment]
Keep the double point notation because it is used in some other positions. 
Decide againts 'all' when no event type is choosen because somebody could think it is an event type. 
See following picture for the solution when no event type is selected.
![cmmn_listener](https://cloud.githubusercontent.com/assets/2493231/16414972/23f910ea-3d3b-11e6-9c1c-81fd7015bb46.png)
